name: Arduino CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        board: [esp32dev, nodemcu]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1
      with:
        enable-ini-overrides: true
        
    - name: Install ESP32 Board
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32
    
    - name: Compile ESP-IoT-WebControl
      run: arduino-cli compile --fqbn esp32:esp32:esp32dev ESP-IoT-WebControl.ino
